# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [1]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [2]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1, 2, 3, 4, 5])

# O un array de dos dimensiones (bidimensional)
array_bidim = np.array([[1, 2, 3],
                        [4, 5, 6]])

# O un array de tres dimensiones (tridimensional)
array_tridim = np.array([[[1, 2, 3],
                          [4, 5, 6]],
                         [[7, 8, 9],
                          [10, 11, 12]]])

In [3]:
# Array de una dimensión
array_unidim

array([1, 2, 3, 4, 5])

In [4]:
# Array de dos dimensiones
array_bidim

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Array de tres dimensiones
array_tridim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [6]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
print("\nArray Unidimensional: \n" , array_unidim)
print("\nForma: \n"                , array_unidim.shape)  # vector 5 elementos
print("\nNumero de dimensiones: \n", array_unidim.ndim)   # 1 dimension
print("\nTipos de datos: \n"       , array_unidim.dtype)  # int32
print("\nTamaño: \n"               , array_unidim.size)   # 5
print("\nTipo: \n"                 , type(array_unidim))  # <class 'numpy.ndarray'>


Array Unidimensional: 
 [1 2 3 4 5]

Forma: 
 (5,)

Numero de dimensiones: 
 1

Tipos de datos: 
 int32

Tamaño: 
 5

Tipo: 
 <class 'numpy.ndarray'>


In [7]:
# Atributos del array bidimensional
print("\nArray Bidimensional: \n"  , array_bidim)
print("\nForma: \n"                , array_bidim.shape)  # matriz de 2 filas x 3 columnas
print("\nNumero de dimensiones: \n", array_bidim.ndim)   # 2 dimensiones
print("\nTipos de datos: \n"       , array_bidim.dtype)  # int32
print("\nTamaño: \n"               , array_bidim.size)   # 6
print("\nTipo: \n"                 , type(array_bidim))  # <class 'numpy.ndarray'> 


Array Bidimensional: 
 [[1 2 3]
 [4 5 6]]

Forma: 
 (2, 3)

Numero de dimensiones: 
 2

Tipos de datos: 
 int32

Tamaño: 
 6

Tipo: 
 <class 'numpy.ndarray'>


In [8]:
# Atributos del array tridimensional
print("\nArray Tridimensional: \n" , array_tridim)
print("\nForma: \n"                , array_tridim.shape)  # 2 matrices, cada una de 2 filas x 3 columnas
print("\nNumero de dimensiones: \n", array_tridim.ndim)   # 3 dimensiones
print("\nTipos de datos: \n"       , array_tridim.dtype)  # int32
print("\nTamaño: \n"               , array_tridim.size)   # 12
print("\nTipo: \n"                 , type(array_tridim))  # <class 'numpy.ndarray'>


Array Tridimensional: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Forma: 
 (2, 2, 3)

Numero de dimensiones: 
 3

Tipos de datos: 
 int32

Tamaño: 
 12

Tipo: 
 <class 'numpy.ndarray'>


In [9]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
"""
Pandas es el Excel de Python. Un DataFrame es basicamente una tabla de Excel
"""
import pandas as pd
datos_bidim = pd.DataFrame(array_bidim)
datos_bidim

0  1  2
0  1  2  3
1  4  5  6

In [10]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
"""
matriz de 4 filas x 3 columnas
"""
array_bidim_unos = np.ones((4, 3))
array_bidim_unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
"""
2 matrices de 4 filas x 3 columnas
"""
array_tridim_ceros = np.zeros((2, 4, 3))
array_tridim_ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 101, 5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [13]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
"""
random.randint genera numeros aleatorios, en este caso generara valores entre 0 <= x < 10
El tecer valor pasado a la funcion random.randint es una tupla donde se especifica las filas y columnas
"""
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[9, 8, 6, 9, 4],
       [4, 1, 7, 5, 5]])

In [14]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
"""
random.random retorna un valor entre 0 y 1
"""
array_3 = np.random.random((3, 5))
array_3

array([[0.76567362, 0.34538604, 0.86493826, 0.96927667, 0.35901092],
       [0.95522996, 0.3123348 , 0.13044263, 0.57582849, 0.69811679],
       [0.12156838, 0.38982883, 0.78230445, 0.87751391, 0.55307985]])

In [15]:
# Establecer semilla de números aleatorios en 27
"""
Con esto la funcion np.random generara siempre los mismos resultados, ya que tiene una semilla definida
"""
np.random.seed(27)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
"""
random.randint genera numeros aleatorios, en este caso generara valores entre 0 <= x < 10
El tercer valor pasado a la funcion random.randint es una tupla donde se especifica las filas y columnas
"""
array_4 = np.random.randint(0, 10, (3, 5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [16]:
# Encontramos los valores únicos del array_4
"""
Obtiene un array con valores unicos que obtiene analizando de forma recursiva array_4
"""
array_4_unique = np.unique(array_4)
array_4_unique

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [17]:
# Extraemos el elemento de índice 0 del array_4
array_4[0]

array([3, 8, 8, 8, 0])

In [18]:
# Extraemos las primeras dos filas del array_4
"""
[:2], filas con indice 0, 1
"""
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [19]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
"""
[:2, :3], filas con indice 0, 1 y columnas con indice 0, 1, 2
"""
array_4[:2, :3]

array([[3, 8, 8],
       [5, 8, 9]])

In [20]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))

In [21]:
# invocamos el array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [22]:
# invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# Sumamos los dos arrays
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [24]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# Intentaremos sumar los arrays 6 y 7
"""
Esto genera error porque no se pueden sumar arrays con diferentes formas
array_6 + array_7
"""

'\nEsto genera error porque no se pueden sumar arrays con diferentes formas\narray_6 + array_7\n'

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [26]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
array_8 = np.ones((4, 3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# Restamos el array_8 al array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [29]:
# invocamos el array_9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [30]:
# invocamos el array_10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [31]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [32]:
# Elevamos el array_9 al cuadrado
array_9**2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [33]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [34]:
# Hallamos el promedio de los valores del array_9
"""
mean es la Media o Promedio
"""
array_9.mean()

3.0

In [35]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

4

In [36]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

1

In [37]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
"""
9 filas x 1 columna
"""
array_11 = array_9.reshape((9, 1))

In [38]:
# invocamos el array_11
array_11

array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [39]:
# Transponemos el array_11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [40]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [41]:
# Obtener el tipo de datos del array_12
type(array_12)

numpy.ndarray

In [42]:
# Obtener el tipo de datos de los elementos en el array_12
array_12.dtype

dtype('bool')

In [43]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
array_9 == array_10

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [44]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [45]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [46]:
# Ordenamos de menor a mayor los elementos dentro del array_9
"""
Obtenemos los elementos ordenados de menor a mayor en cada fila
"""
np.sort(array_9)

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [47]:
# Ordenamos de mayor a menor los elementos dentro del array_9
"""
Obtenemos los elementos ordenados de mayor a menor en cada fila
"""
-np.sort(-array_9)

array([[4, 3, 2],
       [4, 4, 1],
       [4, 3, 2]])